version: "3.9"

services:
  db:
    ports: ["127.0.0.1:5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    ports: ["127.0.0.1:6379:6379"]
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    volumes:
      - ./app:/app/app
      - ./alembic.ini:/app/alembic.ini
      - ./db/migrations:/app/db/migrations
      - ./rules.yml:/app/rules.yml
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/package.json:/app/package.json
      - ./frontend/package-lock.json:/app/package-lock.json

volumes:
  postgres_data:
  redis_data:
