version: "3.8"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      CORS_ORIGINS: '["http://localhost:5173"]'
      API_KEY: "${API_KEY}"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mastowatch
      POSTGRES_USER: mastowatch
      POSTGRES_PASSWORD: mastowatch
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mastowatch -d mastowatch"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes"]

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
    command: ["alembic", "upgrade", "head"]

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - api
      - redis
    environment:
      <<: *backend-env
    restart: on-failure
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "--concurrency=2"]

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - worker
    environment:
      <<: *backend-env
    restart: on-failure
    command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=INFO"]
      - api
      - redis
    environment:
      <<: *backend-env
    restart: on-failure
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "--concurrency=2"]

  beat:
    <<: *backend
    depends_on:
      - worker
    environment:
      <<: *backend-env
    restart: on-failure
    command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=INFO"]
    command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=INFO"]
