version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mastowatch
      POSTGRES_USER: mastowatch
      POSTGRES_PASSWORD: mastowatch
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mastowatch -d mastowatch"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports: ["6379:6379"]
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    environment:
      MST_BASE_URL: "https://your.instance"
      BOT_TOKEN: "REPLACE_WITH_BOT_TOKEN"
      ADMIN_TOKEN: "REPLACE_WITH_ADMIN_TOKEN"
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
      REDIS_URL: "redis://redis:6379/0"
      DRY_RUN: "true"
      BATCH_SIZE: "80"
    ports: ["8080:8080"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
    command: ["alembic", "upgrade", "head"]

  worker:
    build: .
    depends_on:
      - api
      - redis
    environment:
      MST_BASE_URL: "https://your.instance"
      BOT_TOKEN: "REPLACE_WITH_BOT_TOKEN"
      ADMIN_TOKEN: "REPLACE_WITH_ADMIN_TOKEN"
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
      REDIS_URL: "redis://redis:6379/0"
      DRY_RUN: "true"
      BATCH_SIZE: "80"
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "--concurrency=2"]

  beat:
    build: .
    depends_on:
      - worker
    environment:
      MST_BASE_URL: "https://your.instance"
      BOT_TOKEN: "REPLACE_WITH_BOT_TOKEN"
      ADMIN_TOKEN: "REPLACE_WITH_ADMIN_TOKEN"
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
      REDIS_URL: "redis://redis:6379/0"
      DRY_RUN: "true"
      BATCH_SIZE: "80"
    command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=INFO"]
