version: "3.9"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mastowatch
      POSTGRES_USER: mastowatch
      POSTGRES_PASSWORD: mastowatch
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mastowatch -d mastowatch"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    ports: ["6379:6379"]
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    environment:
      INSTANCE_BASE: "${INSTANCE_BASE}"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      BOT_TOKEN: "${BOT_TOKEN}"
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
      REDIS_URL: "redis://redis:6379/0"
      DRY_RUN: "true"
      BATCH_SIZE: "80"
      MAX_STATUSES_TO_FETCH: "100"
      REPORT_CATEGORY_DEFAULT: "spam"
      FORWARD_REMOTE_REPORTS: "false"
      POLICY_VERSION: "v1"
      API_KEY: "${API_KEY}"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
      CORS_ORIGINS: '["http://localhost:5173"]'
    ports: ["8080:8080"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]

  migrate:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
    command: ["alembic", "upgrade", "head"]

  worker:
    build: .
    depends_on:
      - api
      - redis
    environment:
      INSTANCE_BASE: "${INSTANCE_BASE}"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      BOT_TOKEN: "${BOT_TOKEN}"
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
      REDIS_URL: "redis://redis:6379/0"
      DRY_RUN: "true"
      BATCH_SIZE: "80"
      MAX_STATUSES_TO_FETCH: "100"
      REPORT_CATEGORY_DEFAULT: "spam"
      FORWARD_REMOTE_REPORTS: "false"
      POLICY_VERSION: "v1"
      API_KEY: "${API_KEY}"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
      CORS_ORIGINS: '["http://localhost:5173"]'
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "--concurrency=2"]

  beat:
    build: .
    depends_on:
      - worker
    environment:
      INSTANCE_BASE: "${INSTANCE_BASE}"
      ADMIN_TOKEN: "${ADMIN_TOKEN}"
      BOT_TOKEN: "${BOT_TOKEN}"
      DATABASE_URL: "postgresql+psycopg://mastowatch:mastowatch@db:5432/mastowatch"
      REDIS_URL: "redis://redis:6379/0"
      DRY_RUN: "true"
      BATCH_SIZE: "80"
      MAX_STATUSES_TO_FETCH: "100"
      REPORT_CATEGORY_DEFAULT: "spam"
      FORWARD_REMOTE_REPORTS: "false"
      POLICY_VERSION: "v1"
      API_KEY: "${API_KEY}"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
      CORS_ORIGINS: '["http://localhost:5173"]'
    command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=INFO"]
