version: "3.8"

# Shared environment variables
x-backend-env: &backend-env
  INSTANCE_BASE: "${INSTANCE_BASE}"
  ADMIN_TOKEN: "${ADMIN_TOKEN}"
  BOT_TOKEN: "${BOT_TOKEN}"
  DATABASE_URL: "${DATABASE_URL}"
  REDIS_URL: "${REDIS_URL}"
  API_KEY: "${API_KEY}"
  WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
  DRY_RUN: "${DRY_RUN:-true}"
  PANIC_STOP: "${PANIC_STOP:-false}"
  CORS_ORIGINS: '${CORS_ORIGINS:-["http://localhost:3000"]}'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: [.env]
    environment:
      <<: *backend-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://localhost:8080/healthz').getcode()==200 else 1)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.tasks.celery_app", "worker", "--loglevel=INFO", "--concurrency=2"]
    env_file: [.env]
    environment:
      <<: *backend-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    healthcheck:
      # Verify Redis is reachable (simple k8s-compatible exec probe)
      test: ["CMD-SHELL","python -c \"import os,sys; import redis; r=redis.from_url(os.getenv('REDIS_URL')); sys.exit(0 if r.ping() else 1)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["celery", "-A", "app.tasks.celery_app", "beat", "--loglevel=INFO"]
    env_file: [.env]
    environment:
      <<: *backend-env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL","python -c \"import os,sys; import redis; r=redis.from_url(os.getenv('REDIS_URL')); sys.exit(0 if r.ping() else 1)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["alembic", "upgrade", "head"]
    env_file: [.env]
    environment:
      <<: *backend-env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mastowatch
      POSTGRES_USER: mastowatch
      POSTGRES_PASSWORD: mastowatch
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mastowatch -d mastowatch"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8
    command: ["redis-server", "--appendonly", "yes"]
