# --------------------------------------
# Ruff
# --------------------------------------
[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
# Core, high-signal rule families
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
]

# Re-enable only the “docstring required” subset; skip the detailed style police.
extend-select = ["D100", "D101", "D102", "D103"]  # require module / class / func docstrings

# Global ignores (keep the two that already existed, plus drop noisy docstring mood/spacing rules)
ignore = [
  "D203",  # 1 blank line required before class docstring (conflicts with D211)
  "D213",  # Multi-line docstring summary should start at second line (conflicts with D212)
  "D401",  # First line should be in imperative mood – stylistic, not critical
]

[tool.ruff.lint.per-file-ignores]
# FastAPI Depends in default args is the framework's recommended pattern
"backend/app/api/*.py" = ["B008"]
# Tests can have long lines and don't need full docstring coverage
"tests/**/*.py" = ["E501", "D100", "D101", "D102", "D103"]
# conftest.py needs to set env vars before importing app modules
"tests/conftest.py" = ["E402"]
# Models are often self-documenting via type hints
"backend/app/models.py" = ["D101"]


